name: Build Vita App

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        # POPRAWKA: W tym kontenerze nie wpisujemy "install".
        # Podajemy tylko nazwy paczek po kolei.
        vdpm vita2d
        vdpm curl
        vdpm zlib
        vdpm libpng
        vdpm libjpeg-turbo
        vdpm openssl
        
    - name: Compile
      run: |
        cmake .
        make
        
    - name: Upload VPK
      uses: actions/upload-artifact@v4
      with:
        name: MyrientBrowser
        path: myrient_app.vpk
