name: Build Vita App

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        # Pobieramy biblioteki homebrew z repozytorium VitaSDK
        # Używamy najnowszych nazw pakietów
        vdpm install vita2d curl zlib libpng libjpeg-turbo
        
    - name: Compile
      run: |
        cmake -DCMAKE_TOOLCHAIN_FILE=$VITASDK/share/vita.toolchain.cmake .
        make
        
    - name: Upload VPK
      uses: actions/upload-artifact@v4
      with:
        name: MyrientBrowser
        path: myrient_app.vpk
