name: Build Vita App

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        # NAPRAWA: W tym obrazie "install" jest dodawane z automatu.
        # Dlatego podajemy TYLKO nazwy paczek.
        # Wymieniamy wszystko, co jest potrzebne do Curl i Vita2D.
        vdpm vita2d curl mbedtls zlib libpng libjpeg-turbo
        
    - name: Compile
      run: |
        # Wymuszamy użycie pliku toolchain, żeby CMake wiedział gdzie co jest
        cmake -DCMAKE_TOOLCHAIN_FILE=$VITASDK/share/vita.toolchain.cmake .
        make
        
    - name: Upload VPK
      uses: actions/upload-artifact@v4
      with:
        name: MyrientBrowser
        path: myrient_app.vpk
