name: Build Vita App

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        # To jest ten brakujący krok!
        # Robot pobiera biblioteki i pliki nagłówkowe
        vdpm install vita2d curlssl libpng zlib jpeg
        
    - name: Compile
      run: |
        # Konfiguracja i budowanie
        cmake -DCMAKE_TOOLCHAIN_FILE=$VITASDK/share/vita.toolchain.cmake .
        make
        
    - name: Upload VPK
      uses: actions/upload-artifact@v4
      with:
        name: MyrientBrowser
        path: myrient_app.vpk
